if-shell -b '[ "$(uname)" = "Darwin" ]' {
    set default-shell /usr/local/bin/zsh
    COPY_CMD="pbcopy"
}

if-shell -b '[ "$(uname)" = "Linux" ]' {
    set default-shell /bin/zsh
    COPY_CMD="wl-copy"
}

set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"

setw -g xterm-keys on
set -sg escape-time 0
set -sg repeat-time 0
set -s focus-events on
set -g mouse on
set -q -g status-utf8 on
setw -q -g utf8 on
setw -g history-limit 50000000

tmux_conf_copy_to_os_clipboard=true

set -g status-keys vi
set -g mode-keys vi

set -g status-position top

set -g base-index 1
setw -g pane-base-index 0
setw -g automatic-rename off
set -g renumber-windows on
set -g set-titles off
set -g monitor-activity on
set -g visual-activity off

bind-key -n C-h select-pane -L
bind-key -n C-l select-pane -R

set -g destroy-unattached on

set-option -g status off

bind-key -T root WheelUpPane \
    if-shell -Ft= '#{?mouse_any_flag,1,#{pane_in_mode}}' \
    'send -Mt=' 'if-shell -t= "#{?alternate_on,true,false} || \
        echo \"#{tmux_commands_with_legacy_scroll}\" | grep -q \"#{pane_current_command}\"" \
    "send -t= Up Up Up" "copy-mode -t="'
bind-key -T root WheelDownPane \
    if-shell -Ft= '#{?pane_in_mode,1,#{mouse_any_flag}}' \
    'send -Mt=' 'if-shell -t= "#{?alternate_on,true,false} || \
        echo \"#{tmux_commands_with_legacy_scroll}\" | grep -q \"#{pane_current_command}\"" \
    "send -t= Down Down Down" "send -Mt="'
bind -n MouseDrag1Pane \
    if -Ft= '#{mouse_any_flag}' \
    'if -Ft= \"#{pane_in_mode}\" \
    \"copy-mode -eM\" \
    \"send-keys -M\"' \
    'copy-mode -eM'

bind-key -T root M-z copy-mode

bind-key -T copy-mode-vi v send-keys -X begin-selection

bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel $COPY_CMD
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel $COPY_CMD
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel $COPY_CMD

# split current window horizontally
bind - split-window -v -c '#{pane_current_path}'
# split current window vertically
bind _ split-window -h -c '#{pane_current_path}'
