local plugins = {}

table.insert(plugins, require("plugins.ui.barbar"))
table.insert(plugins, require("plugins.ui.bufresize"))
-- table.insert(plugins, require("plugins.misc.colorful-winsep"))
table.insert(plugins, require("plugins.ui.edgy"))
table.insert(plugins, require("plugins.ui.gitsigns"))
table.insert(plugins, require("plugins.ui.hlchunk"))
table.insert(plugins, require("plugins.ui.hlslens"))
-- table.insert(plugins, require("plugins.ui.indent-blankline"))
table.insert(plugins, require("plugins.ui.lush"))
table.insert(plugins, require("plugins.ui.lualine"))
table.insert(plugins, require("plugins.ui.neo-tree"))
table.insert(plugins, require("plugins.ui.panel"))
-- table.insert(plugins, require("plugins.ui.sidebar"))
-- table.insert(plugins, require("plugins.ui.noice"))
table.insert(plugins, require("plugins.ui.telescope"))
-- table.insert(plugins, require("plugins.ui.tint"))
table.insert(plugins, require("plugins.ui.trouble"))
table.insert(plugins, require("plugins.ui.twighlight"))
table.insert(plugins, require("plugins.ui.which-key"))
table.insert(plugins, require("plugins.ui.window-picker"))
table.insert(plugins, require("plugins.ui.winshift"))
table.insert(plugins, require("plugins.ui.zen-mode"))

return plugins
